import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import SeachFilters from "@/components/search-filters/SeachFilters";
import type { Metadata } from "next";
import { getPayload } from "payload"
import configPromise from "@payload-config";
import { Category } from "@/payload-types";
import { CustomCategory } from "./types";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const payload = await getPayload({
    config:configPromise
  })
  const data = await payload.find({
    collection:'categories',
    pagination:false,
    depth:1,
    where:{
      parent:{
        exists:false
      }
    },
    sort:'name'
  });
  const formattedData:CustomCategory[] = data?.docs?.map((doc)=>({
    ...doc,
    subcategories:doc?.subcategories?.docs?.map((item)=>({
      ...(item as Category),
      subcategories:undefined
    })) || []
  }))
  return (
    <main className="flex flex-col min-h-screen">
        <Navbar/>
        <SeachFilters data={formattedData}/>
        <div className="flex-1 bg-[#f4f4f0]">
        {children}
        </div>
        <Footer/>
        </main>
  );
}
