import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import SeachFilters from "@/components/search-filters/SeachFilters";
import type { Metadata } from "next";
import { dehydrate, HydrationBoundary } from '@tanstack/react-query';
import { getQueryClient, trpc } from "@/trpc/server";
import { Suspense } from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const queryClient = getQueryClient();
    void queryClient.prefetchQuery(trpc.categories.getMany.queryOptions());
    return (
        <main className="flex flex-col min-h-screen">
            <Navbar />
            <HydrationBoundary state={dehydrate(queryClient)}>
                <Suspense fallback={<p>Loading...</p>}>
                    <SeachFilters />
                </Suspense>
            </HydrationBoundary>
            <div className="flex-1 bg-[#f4f4f0]">
                {children}
            </div>
            <Footer />
        </main>
    );
}
